# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/University/GrandFinale/Project/riscv_fpga/RISCV_Demo/RISCV_Demo.srcs/sources_1/bd/Integrated/ip/Integrated_xbar_0/Integrated_xbar_0.xci
# IP: The module: 'Integrated_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/GrandFinale/Project/riscv_fpga/RISCV_Demo/RISCV_Demo.srcs/sources_1/bd/Integrated/ip/Integrated_xbar_0/Integrated_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Integrated_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: e:/University/GrandFinale/Project/riscv_fpga/RISCV_Demo/RISCV_Demo.srcs/sources_1/bd/Integrated/ip/Integrated_xbar_0/Integrated_xbar_0.xci
# IP: The module: 'Integrated_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/GrandFinale/Project/riscv_fpga/RISCV_Demo/RISCV_Demo.srcs/sources_1/bd/Integrated/ip/Integrated_xbar_0/Integrated_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Integrated_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
