# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Integrated/Integrated.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated || ORIG_REF_NAME==Integrated}]

# IP: bd/Integrated/ip/Integrated_processing_system7_0_1/Integrated_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_processing_system7_0_1 || ORIG_REF_NAME==Integrated_processing_system7_0_1}]

# IP: bd/Integrated/ip/Integrated_axi_interconnect_0_0/Integrated_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_axi_interconnect_0_0 || ORIG_REF_NAME==Integrated_axi_interconnect_0_0}]

# IP: bd/Integrated/ip/Integrated_axi_gpio_0_0/Integrated_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_axi_gpio_0_0 || ORIG_REF_NAME==Integrated_axi_gpio_0_0}]

# IP: bd/Integrated/ip/Integrated_axi_bram_ctrl_0_0/Integrated_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Integrated_axi_bram_ctrl_0_0}]

# IP: bd/Integrated/ip/Integrated_blk_mem_gen_0_0/Integrated_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_blk_mem_gen_0_0 || ORIG_REF_NAME==Integrated_blk_mem_gen_0_0}]

# IP: bd/Integrated/ip/Integrated_axi_bram_ctrl_1_0/Integrated_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_axi_bram_ctrl_1_0 || ORIG_REF_NAME==Integrated_axi_bram_ctrl_1_0}]

# IP: bd/Integrated/ip/Integrated_axi_interconnect_1_0/Integrated_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_axi_interconnect_1_0 || ORIG_REF_NAME==Integrated_axi_interconnect_1_0}]

# IP: bd/Integrated/ip/Integrated_proc_sys_reset_0_0/Integrated_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_proc_sys_reset_0_0 || ORIG_REF_NAME==Integrated_proc_sys_reset_0_0}]

# IP: bd/Integrated/ip/Integrated_Write_FIFO_0_0/Integrated_Write_FIFO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_Write_FIFO_0_0 || ORIG_REF_NAME==Integrated_Write_FIFO_0_0}]

# IP: bd/Integrated/ip/Integrated_axi_bram_ctrl_0_1/Integrated_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_axi_bram_ctrl_0_1 || ORIG_REF_NAME==Integrated_axi_bram_ctrl_0_1}]

# IP: bd/Integrated/ip/Integrated_blk_mem_gen_1_0/Integrated_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_blk_mem_gen_1_0 || ORIG_REF_NAME==Integrated_blk_mem_gen_1_0}]

# IP: bd/Integrated/ip/Integrated_RISCV_Proc_AXI_1_0/Integrated_RISCV_Proc_AXI_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_RISCV_Proc_AXI_1_0 || ORIG_REF_NAME==Integrated_RISCV_Proc_AXI_1_0}]

# IP: bd/Integrated/ip/Integrated_xbar_0/Integrated_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_xbar_0 || ORIG_REF_NAME==Integrated_xbar_0}]

# IP: bd/Integrated/ip/Integrated_xbar_1/Integrated_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_xbar_1 || ORIG_REF_NAME==Integrated_xbar_1}]

# IP: bd/Integrated/ip/Integrated_auto_pc_0/Integrated_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_auto_pc_0 || ORIG_REF_NAME==Integrated_auto_pc_0}]

# IP: bd/Integrated/ip/Integrated_auto_pc_1/Integrated_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Integrated_auto_pc_1 || ORIG_REF_NAME==Integrated_auto_pc_1}]

# XDC: bd/Integrated/Integrated_ooc.xdc
