// Copyright 1986-2016 Xilinx, Inc. All Rights Reserved.
// --------------------------------------------------------------------------------
// Tool Version: Vivado v.2016.3 (win64) Build 1682563 Mon Oct 10 19:07:27 MDT 2016
// Date        : Fri Apr 28 08:27:56 2017
// Host        : ASUS-PC running 64-bit major release  (build 9200)
// Command     : write_verilog -force -mode synth_stub
//               E:/University/GrandFinale/Project/riscv_fpga/RISCV_Demo/RISCV_Demo.srcs/sources_1/bd/Integrated/ip/Integrated_RISCV_Proc_AXI_1_0/Integrated_RISCV_Proc_AXI_1_0_stub.v
// Design      : Integrated_RISCV_Proc_AXI_1_0
// Purpose     : Stub declaration of top-level module interface
// Device      : xc7z020clg484-1
// --------------------------------------------------------------------------------

// This empty module with port declaration file causes synthesis tools to infer a black box for IP.
// The synthesis directives are for Synopsys Synplify support to prevent IO buffer insertion.
// Please paste the declaration into a Verilog source file or add the file as an additional source.
(* X_CORE_INFO = "RISCV_Proc_AXI,Vivado 2016.3" *)
module Integrated_RISCV_Proc_AXI_1_0(CLK, EXT_FIFO_WR_ENB, EXT_FIFO_WR_DATA, 
  P0_INIT_AXI_TXN, P0_TXN_DONE, P0_ERROR, M0_AXI_ACLK, M0_AXI_ARESETN, M0_AXI_AWID, 
  M0_AXI_AWADDR, M0_AXI_AWLEN, M0_AXI_AWSIZE, M0_AXI_AWBURST, M0_AXI_AWLOCK, M0_AXI_AWCACHE, 
  M0_AXI_AWPROT, M0_AXI_AWQOS, M0_AXI_AWUSER, M0_AXI_AWVALID, M0_AXI_AWREADY, M0_AXI_WDATA, 
  M0_AXI_WSTRB, M0_AXI_WLAST, M0_AXI_WUSER, M0_AXI_WVALID, M0_AXI_WREADY, M0_AXI_BID, 
  M0_AXI_BRESP, M0_AXI_BUSER, M0_AXI_BVALID, M0_AXI_BREADY, M0_AXI_ARID, M0_AXI_ARADDR, 
  M0_AXI_ARLEN, M0_AXI_ARSIZE, M0_AXI_ARBURST, M0_AXI_ARLOCK, M0_AXI_ARCACHE, M0_AXI_ARPROT, 
  M0_AXI_ARQOS, M0_AXI_ARUSER, M0_AXI_ARVALID, M0_AXI_ARREADY, M0_AXI_RID, M0_AXI_RDATA, 
  M0_AXI_RRESP, M0_AXI_RLAST, M0_AXI_RUSER, M0_AXI_RVALID, M0_AXI_RREADY, P1_INIT_AXI_TXN, 
  P1_TXN_DONE, P1_ERROR, M1_AXI_ACLK, M1_AXI_ARESETN, M1_AXI_AWID, M1_AXI_AWADDR, M1_AXI_AWLEN, 
  M1_AXI_AWSIZE, M1_AXI_AWBURST, M1_AXI_AWLOCK, M1_AXI_AWCACHE, M1_AXI_AWPROT, M1_AXI_AWQOS, 
  M1_AXI_AWUSER, M1_AXI_AWVALID, M1_AXI_AWREADY, M1_AXI_WDATA, M1_AXI_WSTRB, M1_AXI_WLAST, 
  M1_AXI_WUSER, M1_AXI_WVALID, M1_AXI_WREADY, M1_AXI_BID, M1_AXI_BRESP, M1_AXI_BUSER, 
  M1_AXI_BVALID, M1_AXI_BREADY, M1_AXI_ARID, M1_AXI_ARADDR, M1_AXI_ARLEN, M1_AXI_ARSIZE, 
  M1_AXI_ARBURST, M1_AXI_ARLOCK, M1_AXI_ARCACHE, M1_AXI_ARPROT, M1_AXI_ARQOS, M1_AXI_ARUSER, 
  M1_AXI_ARVALID, M1_AXI_ARREADY, M1_AXI_RID, M1_AXI_RDATA, M1_AXI_RRESP, M1_AXI_RLAST, 
  M1_AXI_RUSER, M1_AXI_RVALID, M1_AXI_RREADY)
/* synthesis syn_black_box black_box_pad_pin="CLK,EXT_FIFO_WR_ENB,EXT_FIFO_WR_DATA[31:0],P0_INIT_AXI_TXN,P0_TXN_DONE,P0_ERROR,M0_AXI_ACLK,M0_AXI_ARESETN,M0_AXI_AWID[0:0],M0_AXI_AWADDR[31:0],M0_AXI_AWLEN[7:0],M0_AXI_AWSIZE[2:0],M0_AXI_AWBURST[1:0],M0_AXI_AWLOCK,M0_AXI_AWCACHE[3:0],M0_AXI_AWPROT[2:0],M0_AXI_AWQOS[3:0],M0_AXI_AWUSER[0:0],M0_AXI_AWVALID,M0_AXI_AWREADY,M0_AXI_WDATA[127:0],M0_AXI_WSTRB[15:0],M0_AXI_WLAST,M0_AXI_WUSER[0:0],M0_AXI_WVALID,M0_AXI_WREADY,M0_AXI_BID[0:0],M0_AXI_BRESP[1:0],M0_AXI_BUSER[0:0],M0_AXI_BVALID,M0_AXI_BREADY,M0_AXI_ARID[0:0],M0_AXI_ARADDR[31:0],M0_AXI_ARLEN[7:0],M0_AXI_ARSIZE[2:0],M0_AXI_ARBURST[1:0],M0_AXI_ARLOCK,M0_AXI_ARCACHE[3:0],M0_AXI_ARPROT[2:0],M0_AXI_ARQOS[3:0],M0_AXI_ARUSER[0:0],M0_AXI_ARVALID,M0_AXI_ARREADY,M0_AXI_RID[0:0],M0_AXI_RDATA[127:0],M0_AXI_RRESP[1:0],M0_AXI_RLAST,M0_AXI_RUSER[0:0],M0_AXI_RVALID,M0_AXI_RREADY,P1_INIT_AXI_TXN,P1_TXN_DONE,P1_ERROR,M1_AXI_ACLK,M1_AXI_ARESETN,M1_AXI_AWID[0:0],M1_AXI_AWADDR[31:0],M1_AXI_AWLEN[7:0],M1_AXI_AWSIZE[2:0],M1_AXI_AWBURST[1:0],M1_AXI_AWLOCK,M1_AXI_AWCACHE[3:0],M1_AXI_AWPROT[2:0],M1_AXI_AWQOS[3:0],M1_AXI_AWUSER[0:0],M1_AXI_AWVALID,M1_AXI_AWREADY,M1_AXI_WDATA[127:0],M1_AXI_WSTRB[15:0],M1_AXI_WLAST,M1_AXI_WUSER[0:0],M1_AXI_WVALID,M1_AXI_WREADY,M1_AXI_BID[0:0],M1_AXI_BRESP[1:0],M1_AXI_BUSER[0:0],M1_AXI_BVALID,M1_AXI_BREADY,M1_AXI_ARID[0:0],M1_AXI_ARADDR[31:0],M1_AXI_ARLEN[7:0],M1_AXI_ARSIZE[2:0],M1_AXI_ARBURST[1:0],M1_AXI_ARLOCK,M1_AXI_ARCACHE[3:0],M1_AXI_ARPROT[2:0],M1_AXI_ARQOS[3:0],M1_AXI_ARUSER[0:0],M1_AXI_ARVALID,M1_AXI_ARREADY,M1_AXI_RID[0:0],M1_AXI_RDATA[127:0],M1_AXI_RRESP[1:0],M1_AXI_RLAST,M1_AXI_RUSER[0:0],M1_AXI_RVALID,M1_AXI_RREADY" */;
  input CLK;
  output EXT_FIFO_WR_ENB;
  output [31:0]EXT_FIFO_WR_DATA;
  input P0_INIT_AXI_TXN;
  output P0_TXN_DONE;
  output P0_ERROR;
  input M0_AXI_ACLK;
  input M0_AXI_ARESETN;
  output [0:0]M0_AXI_AWID;
  output [31:0]M0_AXI_AWADDR;
  output [7:0]M0_AXI_AWLEN;
  output [2:0]M0_AXI_AWSIZE;
  output [1:0]M0_AXI_AWBURST;
  output M0_AXI_AWLOCK;
  output [3:0]M0_AXI_AWCACHE;
  output [2:0]M0_AXI_AWPROT;
  output [3:0]M0_AXI_AWQOS;
  output [0:0]M0_AXI_AWUSER;
  output M0_AXI_AWVALID;
  input M0_AXI_AWREADY;
  output [127:0]M0_AXI_WDATA;
  output [15:0]M0_AXI_WSTRB;
  output M0_AXI_WLAST;
  output [0:0]M0_AXI_WUSER;
  output M0_AXI_WVALID;
  input M0_AXI_WREADY;
  input [0:0]M0_AXI_BID;
  input [1:0]M0_AXI_BRESP;
  input [0:0]M0_AXI_BUSER;
  input M0_AXI_BVALID;
  output M0_AXI_BREADY;
  output [0:0]M0_AXI_ARID;
  output [31:0]M0_AXI_ARADDR;
  output [7:0]M0_AXI_ARLEN;
  output [2:0]M0_AXI_ARSIZE;
  output [1:0]M0_AXI_ARBURST;
  output M0_AXI_ARLOCK;
  output [3:0]M0_AXI_ARCACHE;
  output [2:0]M0_AXI_ARPROT;
  output [3:0]M0_AXI_ARQOS;
  output [0:0]M0_AXI_ARUSER;
  output M0_AXI_ARVALID;
  input M0_AXI_ARREADY;
  input [0:0]M0_AXI_RID;
  input [127:0]M0_AXI_RDATA;
  input [1:0]M0_AXI_RRESP;
  input M0_AXI_RLAST;
  input [0:0]M0_AXI_RUSER;
  input M0_AXI_RVALID;
  output M0_AXI_RREADY;
  input P1_INIT_AXI_TXN;
  output P1_TXN_DONE;
  output P1_ERROR;
  input M1_AXI_ACLK;
  input M1_AXI_ARESETN;
  output [0:0]M1_AXI_AWID;
  output [31:0]M1_AXI_AWADDR;
  output [7:0]M1_AXI_AWLEN;
  output [2:0]M1_AXI_AWSIZE;
  output [1:0]M1_AXI_AWBURST;
  output M1_AXI_AWLOCK;
  output [3:0]M1_AXI_AWCACHE;
  output [2:0]M1_AXI_AWPROT;
  output [3:0]M1_AXI_AWQOS;
  output [0:0]M1_AXI_AWUSER;
  output M1_AXI_AWVALID;
  input M1_AXI_AWREADY;
  output [127:0]M1_AXI_WDATA;
  output [15:0]M1_AXI_WSTRB;
  output M1_AXI_WLAST;
  output [0:0]M1_AXI_WUSER;
  output M1_AXI_WVALID;
  input M1_AXI_WREADY;
  input [0:0]M1_AXI_BID;
  input [1:0]M1_AXI_BRESP;
  input [0:0]M1_AXI_BUSER;
  input M1_AXI_BVALID;
  output M1_AXI_BREADY;
  output [0:0]M1_AXI_ARID;
  output [31:0]M1_AXI_ARADDR;
  output [7:0]M1_AXI_ARLEN;
  output [2:0]M1_AXI_ARSIZE;
  output [1:0]M1_AXI_ARBURST;
  output M1_AXI_ARLOCK;
  output [3:0]M1_AXI_ARCACHE;
  output [2:0]M1_AXI_ARPROT;
  output [3:0]M1_AXI_ARQOS;
  output [0:0]M1_AXI_ARUSER;
  output M1_AXI_ARVALID;
  input M1_AXI_ARREADY;
  input [0:0]M1_AXI_RID;
  input [127:0]M1_AXI_RDATA;
  input [1:0]M1_AXI_RRESP;
  input M1_AXI_RLAST;
  input [0:0]M1_AXI_RUSER;
  input M1_AXI_RVALID;
  output M1_AXI_RREADY;
endmodule
