# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/University/GrandFinale/Project/riscv_fpga/RISCV_Demo/RISCV_Demo.srcs/sources_1/bd/Integrated/ip/Integrated_axi_bram_ctrl_0_1/Integrated_axi_bram_ctrl_0_1.xci
# IP: The module: 'Integrated_axi_bram_ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/GrandFinale/Project/riscv_fpga/RISCV_Demo/RISCV_Demo.srcs/sources_1/bd/Integrated/ip/Integrated_axi_bram_ctrl_0_1/Integrated_axi_bram_ctrl_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Integrated_axi_bram_ctrl_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/University/GrandFinale/Project/riscv_fpga/RISCV_Demo/RISCV_Demo.srcs/sources_1/bd/Integrated/ip/Integrated_axi_bram_ctrl_0_1/Integrated_axi_bram_ctrl_0_1.xci
# IP: The module: 'Integrated_axi_bram_ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/GrandFinale/Project/riscv_fpga/RISCV_Demo/RISCV_Demo.srcs/sources_1/bd/Integrated/ip/Integrated_axi_bram_ctrl_0_1/Integrated_axi_bram_ctrl_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Integrated_axi_bram_ctrl_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
